spring.datasource.url=jdbc:postgresql://dpg-d855n9jeo5us73en4fk0-a.oregon-postgres.render.com/nyan_log_db
spring.datasource.username=nyan_log_db_user
spring.datasource.password=yxwq8FZKCmxCtbb83tGXl3KoiDhtGGwF

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
