spring.datasource.url=jdbc:postgresql://dpg-d81s0mcdirrc73d7l3j0-a.oregon-postgres.render.com/nyanlog
spring.datasource.username=nyanlog
spring.datasource.password=1SXkWFQxMCZdjPUv6B90xS7mAHayrgwx

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB